name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
          npm cache clean --force

      - name: Verify build
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
          --tag ${{ secrets.DOCKER_USERNAME }}/mobile-server:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/mobile-server:${{ github.sha }} \
          --cache-from type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mobile-server:buildcache \
          --cache-to type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mobile-server:buildcache,mode=max \
          --output type=docker \
          .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mobile-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mobile-server:${{ github.sha }}

      - name: Scan Docker image
        run: |
          docker scan ${{ secrets.DOCKER_USERNAME }}/mobile-server:latest
