name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Run tests (optional - currently no tests)
    - name: Run tests
      run: npm test

    # Step 5: Lint code (optional - currently no linting)
    - name: Lint code
      run: npm run lint

    # Step 6: Build the application (if required)
    - name: Build application
      run: npm run build

    # Step 7: Deploy to production (example deployment step)
    - name: Deploy to production
      env:
        PORT: ${{ secrets.PORT }}
        MONGOURI: ${{ secrets.MONGOURI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        echo "Starting application..."
        npm start